version: '3.8'

services:
  db:
    image: postgres:alpine3.20
    container_name: postgres_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gestor_financeiro
