version: '3.8'

services:
  db:
    image: postgres:alpine3.20
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gestor_financeiro
    cap_add:
      - "SYS_NICE"

  app:
    build: ./
    container_name: api-gestor-financeiro
    depends_on:
      - db
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gestor_financeiro
