spring:
    datasource:
        url: jdbc:h2:mem:deliveryDB
        username: root
        password:
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true